name: pnpm build and publish

# 执行脚本的生命周期
on:
  #选择在 push 到 github 时触发工作流
  push:
    #分支可以选择多个
    branches: [main]

# 一个 workflow 可以有多个 job
jobs:
  build:
    permissions:
      id-token: write
      contents: write
    # 指定操作系统为'ubuntu-latest'
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Node env setup
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm
          registry-url: 'https://registry.npmjs.org'

      - run: pnpm i

      - run: pnpm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

